## Are these two metrics correlated?

```{r}
#| dev.args: !expr 'list(bg="transparent")'
#| fig.height: 2.5

s1 <- get_ts(base = 10000, noise = 0.1, start = Sys.Date() - 45, trend = 0.5)
s2 <- get_ts(base = 50000, noise = 0.05, start = Sys.Date() - 45, trend = 0.9)

ggplot(s1, aes(x = date, y = value)) +
  geom_line(color = s_line_1, linewidth = 1.1) +
  labs(title = "Orders") +
  scale_y_continuous(expand = c(0,0), limits = ~ c(0, max(.x) * 1.1), label = comma) +
  theme_main +
  theme(axis.title.y = element_blank())

ggplot(s2, aes(x = date, y = value)) +
  geom_line(color = s_line_1, linewidth = 1.1) +
  labs(title = "Social Media Engagement") +
  scale_y_continuous(expand = c(0,0), limits = ~ c(0, max(.x) * 1.1), label = comma) +
  theme_main +
  theme(axis.title.y = element_blank())
```

## A scatterplot, perhaps?

```{r}
#| dev.args: !expr 'list(bg="transparent")'

fd_scatter <- s2 |> 
  left_join(s1, by = c(date = "date"))

ggplot(fd_scatter, aes(x = value.x, y = value.y)) +
  geom_point(color = s_line_1, size = 2) +
  labs(x = "Social Media Engagement",
       y = "Orders") +
  scale_x_continuous(expand = c(0,0), limits = ~ c(min(.x) * 0.95, max(.x) * 1.05), 
                     label = comma) +
  scale_y_continuous(expand = c(0,0), limits = ~ c(min(.x) * 0.95, max(.x) * 1.05), 
                     label = comma) +
  theme_main +
  theme(axis.title.x = element_text(family = "s_font", size = s_axis_title_size, 
                                    face = "bold", colour = s_labels, 
                                    margin = margin(8, 0, 0, 0, "pt")))

```

. . .

:::{.absolute top=185 left=170}

R^2^ = `r cor(fd_scatter$value.x, fd_scatter$value.y)^2 |> round(2)`

:::
